package id.ac.poliban.mi.auzan.listviewpahlawan;

import java.util.ArrayList;
import java.util.List;

public class PahlawanData {
    static List<Pahlawan> getAllPahlawans(){
        List<Pahlawan> data = new ArrayList<>();
        {
            data.add(new Pahlawan("https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Presiden_Sukarno.jpg/220px-Presiden_Sukarno.jpg", "Dr.(H.C.) Ir. H. Soekarno", "Dr.(H.C.) Ir. H. Soekarno1 (ER, EYD: Sukarno, nama lahir: Koesno Sosrodihardjo) (lahir di Surabaya, Jawa Timur, 6 Juni 1901 – meninggal di Jakarta, 21 Juni 1970 pada umur 69 tahun)[note 1][note 2] adalah Presiden pertama Republik Indonesia yang menjabat pada periode 1945–1967.[5]:11, 81 Ia memainkan peranan penting dalam memerdekakan bangsa Indonesia dari penjajahan Belanda.[6]:26-32 Ia adalah Proklamator Kemerdekaan Indonesia (bersama dengan Mohammad Hatta) yang terjadi pada tanggal 17 Agustus 1945. Soekarno adalah yang pertama kali mencetuskan konsep mengenai Pancasila sebagai dasar negara Indonesia dan ia sendiri yang menamainya.[6] "));
            data.add(new Pahlawan("https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/VP_Hatta.jpg/220px-VP_Hatta.jpg", "Dr. (H.C.) Drs. H. Mohammad Hatta", "Dr. (H.C.) Drs. H. Mohammad Hatta (populer sebagai Bung Hatta; lahir dengan nama Mohammad Athar di Fort de Kock, Hindia Belanda, 12 Agustus 1902 – meninggal di Jakarta, 14 Maret 1980 pada umur 77 tahun) adalah negarawan dan ekonom Indonesia yang menjabat sebagai Wakil Presiden Indonesia pertama. Ia bersama Soekarno memainkan peranan sentral dalam perjuangan kemerdekaan Indonesia dari penjajahan Belanda sekaligus memproklamirkannya pada 17 Agustus 1945. Ia pernah menjabat sebagai Perdana Menteri dalam Kabinet Hatta I, Hatta II, dan RIS. Pada 1956, ia mundur dari jabatan wakil presiden karena berselisih dengan Presiden Soekarno. "));
            data.add(new Pahlawan("https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Sudirman.jpg/220px-Sudirman.jpg", "Jenderal Besar Raden Soedirman", "Jenderal Besar Raden Soedirman (EYD: Sudirman; lahir 24 Januari 1916 – meninggal 29 Januari 1950 pada umur 34 tahun[a]) adalah seorang perwira tinggi Indonesia pada masa Revolusi Nasional Indonesia. Sebagai panglima besar Tentara Nasional Indonesia pertama, ia adalah sosok yang dihormati di Indonesia. Terlahir dari pasangan rakyat biasa di Purbalingga, Hindia Belanda, Soedirman diadopsi oleh pamannya yang seorang priyayi. Setelah keluarganya pindah ke Cilacap pada tahun 1916, Soedirman tumbuh menjadi seorang siswa rajin; ia sangat aktif dalam kegiatan ekstrakurikuler, termasuk mengikuti program kepanduan yang dijalankan oleh organisasi Islam Muhammadiyah. Saat di sekolah menengah, Soedirman mulai menunjukkan kemampuannya dalam memimpin dan berorganisasi, dan dihormati oleh masyarakat karena ketaatannya pada Islam. Setelah berhenti kuliah keguruan, pada 1936 ia mulai bekerja sebagai seorang guru, dan kemudian menjadi kepala sekolah, di sekolah dasar Muhammadiyah; ia juga aktif dalam kegiatan Muhammadiyah lainnya dan menjadi pemimpin Kelompok Pemuda Muhammadiyah pada tahun 1937. Setelah Jepang menduduki Hindia Belanda pada 1942, Soedirman tetap mengajar. Pada tahun 1944, ia bergabung dengan tentara Pembela Tanah Air (PETA) yang disponsori Jepang, menjabat sebagai komandan batalion di Banyumas. Selama menjabat, Soedirman bersama rekannya sesama prajurit melakukan pemberontakan, namun kemudian diasingkan ke Bogor. "));
            data.add(new Pahlawan("https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Diponegoro.jpg/220px-Diponegoro.jpg", "Pangeran Diponegoro", "Pangeran Diponegoro adalah putra sulung dari Sultan Hamengkubuwana III, raja ketiga di Kesultanan Yogyakarta. Lahir pada tanggal 11 November 1785 di Yogyakarta dengan nama Mustahar dari seorang selir bernama R.A. Mangkarawati, yaitu seorang garwa ampeyan (istri selir) yang berasal dari Pacitan. Semasa kecilnya, Pangeran Diponegoro bernama Bendara Raden Mas Antawirya.[1]"));
            data.add(new Pahlawan("https://upload.wikimedia.org/wikipedia/id/c/ca/Ki_hajar_dewantara.jpg", "Ki Hajar Dewantara", "Raden Mas Soewardi Soerjaningrat (EBI: Suwardi Suryaningrat, sejak 1922 menjadi Ki Hadjar Dewantara, EBI: Ki Hajar Dewantara, beberapa menuliskan bunyi bahasa Jawanya dengan Ki Hajar Dewantoro; lahir di Pakualaman, 2 Mei 1889 – meninggal di Yogyakarta, 26 April 1959 pada umur 69 tahun;[1] selanjutnya disingkat sebagai Soewardi atau KHD) adalah aktivis pergerakan kemerdekaan Indonesia, kolumnis, politisi, dan pelopor pendidikan bagi kaum pribumi Indonesia dari zaman penjajahan Belanda. Ia adalah pendiri Perguruan Taman Siswa, suatu lembaga pendidikan yang memberikan kesempatan bagi para pribumi untuk bisa memperoleh hak pendidikan seperti halnya para priyayi maupun orang-orang Belanda. "));
            data.add(new Pahlawan("https://upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Bung_Tomo.jpg/220px-Bung_Tomo.jpg", "Bung Tomo", "Sutomo (lahir di Surabaya, Jawa Timur, 3 Oktober 1920 – meninggal di Padang Arafah, Arab Saudi, 7 Oktober 1981 pada umur 61 tahun)[1] lebih dikenal dengan sapaan akrab oleh rakyat sebagai Bung Tomo, adalah pahlawan yang terkenal karena peranannya dalam membangkitkan semangat rakyat untuk melawan kembalinya penjajah Belanda melalui tentara NICA, yang berakhir dengan pertempuran 10 November 1945 yang hingga kini diperingati sebagai Hari Pahlawan. "));
            data.add(new Pahlawan("https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/COLLECTIE_TROPENMUSEUM_Portret_van_Raden_Ajeng_Kartini_TMnr_10018776.jpg/200px-COLLECTIE_TROPENMUSEUM_Portret_van_Raden_Ajeng_Kartini_TMnr_10018776.jpg", "R.A. Kartini", "Raden Adjeng Kartini (lahir di Jepara, Hindia Belanda, 21 April 1879 – meninggal di Rembang, Hindia Belanda, 17 September 1904 pada umur 25 tahun) atau sebenarnya lebih tepat disebut Raden Ayu Kartini[1] adalah seorang tokoh Jawa dan Pahlawan Nasional Indonesia. Kartini dikenal sebagai pelopor kebangkitan perempuan pribumi. Raden Adjeng Kartini berasal dari kalangan priyayi atau kelas bangsawan Jawa.[2] Ia merupakan putri dari Raden Mas Adipati Ario Sosroningrat, seorang patih yang diangkat menjadi bupati Jepara segera setelah Kartini lahir.[2] Kartini adalah putri dari istri pertama, tetapi bukan istri utama.[2] Ibunya bernama M.A. Ngasirah, putri dari Nyai Haji Siti Aminah dan Kyai Haji Madirono, seorang guru agama di Telukawur, Jepara.[2] Dari sisi ayahnya, silsilah Kartini dapat dilacak hingga Hamengkubuwana VI. Garis keturunan Bupati Sosroningrat bahkan dapat ditilik kembali ke istana Kerajaan Majapahit.[2] Semenjak Pangeran Dangirin menjadi bupati Surabaya pada abad ke-18, nenek moyang Sosroningrat mengisi banyak posisi penting di Pangreh Praja.[2]"));
            data.add(new Pahlawan("https://upload.wikimedia.org/wikipedia/id/thumb/c/c8/Pangeran_Antasari_Museum_Lambung_Mangkurat.JPG/220px-Pangeran_Antasari_Museum_Lambung_Mangkurat.JPG", "Pangeran Antasari", "Pangeran Antasari (lahir di Kayu Tangi, Kesultanan Banjar, 1797[1][2] atau 1809[3][4][5][6] – meninggal di Bayan Begok, Hindia Belanda, 11 Oktober 1862 pada umur 53 tahun) adalah seorang Pahlawan Nasional Indonesia. Ia adalah Sultan Banjar.[7] Pada 14 Maret 1862, dia dinobatkan sebagai pimpinan pemerintahan tertinggi di Kesultanan Banjar (Sultan Banjar) dengan menyandang gelar Panembahan Amiruddin Khalifatul Mukminin dihadapan para kepala suku Dayak dan adipati (gubernur) penguasa wilayah Dusun Atas, Kapuas dan Kahayan yaitu Tumenggung Surapati/Tumenggung Yang Pati Jaya Raja.\n" + "Dia cucu Pangeran Amir yang gagal naik tahta pada tahun 1785.[15][16] Pangeran Antasari tidak hanya dianggap sebagai pemimpin Suku Banjar, dia juga merupakan pemimpin Suku Ngaju, Maanyan, Siang, Sihong, Kutai, Pasir, Murung, Bakumpai dan beberapa suku lainya yang berdiam di kawasan dan pedalaman atau sepanjang Sungai Barito, baik yang beragama Islam maupun Kaharingan."));
            data.add(new Pahlawan("https://upload.wikimedia.org/wikipedia/id/1/17/Pattimura_2.jpg", "Kapitan Pattimura", "Pattimura (Thomas Matulessy) lahir di Haria, pulau Saparua, Maluku, 8 Juni 1783 – meninggal di Ambon, Maluku, 16 Desember 1817 pada umur 34 tahun), juga dikenal dengan nama Kapitan Pattimura adalah Pahlawan nasional Indonesia dari Maluku.\n" +
                    "\n" +
                    "Menurut buku biografi Pattimura versi pemerintah yang pertama kali terbit, M Sapija menulis, \"Bahwa pahlawan Pattimura tergolong turunan bangsawan dan berasal dari Nusa Ina (Seram)\". Ayahnya yang bernama Antoni Matulessy adalah anak dari Kasimiliali Pattimura Mattulessy. Yang terakhir ini adalah putra raja Sahulau. Sahulau merupakan nama orang di negeri yang terletak dalam sebuah teluk di Seram.\n" +
                    "\n" +
                    "Namanya kini diabadikan untuk Universitas Pattimura, Kodam XVI/Pattimura dan Bandar Udara Pattimura di Ambon. "));
            data.add(new Pahlawan("https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/Tjoet_Nya%27_Dhien.jpg/220px-Tjoet_Nya%27_Dhien.jpg", "Cut Nyak Dhien", "Cut Nyak Dhien (ejaan lama: Tjoet Nja' Dhien, Lampadang, Kerajaan Aceh, 1848 – Sumedang, Jawa Barat, 6 November 1908; dimakamkan di Gunung Puyuh, Sumedang) adalah seorang Pahlawan Nasional Indonesia dari Aceh yang berjuang melawan Belanda pada masa Perang Aceh. Setelah wilayah VI Mukim diserang, ia mengungsi, sementara suaminya Ibrahim Lamnga bertempur melawan Belanda. Tewasnya Ibrahim Lamnga di Gle Tarum pada tanggal 29 Juni 1878 kemudian menyeret Cut Nyak Dhien lebih jauh dalam perlawanannya terhadap Belanda.\n" +
                    "\n" +
                    "Pada tahun 1880, Cut Nyak Dhien menikah dengan Teuku Umar, setelah sebelumnya ia dijanjikan dapat ikut turun di medan perang jika menerima lamaran tersebut. Dari pernikahan ini Cut Nyak Dhien memiliki seorang anak yang diberi nama Cut Gambang[1]. Setelah pernikahannya dengan Teuku Umar, Cut Nyak Dhien bersama Teuku Umar bertempur bersama melawan Belanda. Namun, pada tanggal 11 Februari 1899 Teuku Umar gugur. Hal ini membuat Cut Nyak Dhien berjuang sendirian di pedalaman Meulaboh bersama pasukan kecilnya. Usia Cut Nyak Dien yang saat itu sudah relatif tua serta kondisi tubuh yang digrogoti berbagai penyakit seperti encok dan rabun membuat satu pasukannya yang bernama Pang Laot melaporkan keberadaannya karena iba.[2][3] Ia akhirnya ditangkap dan dibawa ke Banda Aceh. Di sana ia dirawat dan penyakitnya mulai sembuh. Keberadaan Cut Nyak Dhien yang dianggap masih memberikan pengaruh kuat terhadap perlawanan rakyat Aceh serta hubungannya dengan pejuang Aceh yang belum tertangkap membuatnya kemudian diasingkan ke Sumedang. Cut Nyak Dhien meninggal pada tanggal 6 November 1908 dan dimakamkan di Gunung Puyuh, Sumedang. Nama Cut Nyak Dhien kini diabadikan sebagai Bandar Udara Cut Nyak Dhien Nagan Raya di Meulaboh. "));
        }
        return data;
    }
}
